# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\program\qtsesigner\test_and_prototype\demons_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1158, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Plot_area = QtWidgets.QWidget(self.centralwidget)
        self.Plot_area.setGeometry(QtCore.QRect(400, 60, 471, 441))
        self.Plot_area.setObjectName("Plot_area")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(71, 53, 315, 453))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.Round_time = QtWidgets.QSpinBox(self.widget)
        self.Round_time.setMinimumSize(QtCore.QSize(200, 50))
        self.Round_time.setObjectName("Round_time")
        self.gridLayout.addWidget(self.Round_time, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 2)
        self.Sleeping_time = QtWidgets.QSpinBox(self.widget)
        self.Sleeping_time.setMinimumSize(QtCore.QSize(200, 50))
        self.Sleeping_time.setObjectName("Sleeping_time")
        self.gridLayout.addWidget(self.Sleeping_time, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.Start_fre = QtWidgets.QDoubleSpinBox(self.widget)
        self.Start_fre.setMinimumSize(QtCore.QSize(200, 50))
        self.Start_fre.setMaximum(500.0)
        self.Start_fre.setSingleStep(0.001)
        self.Start_fre.setObjectName("Start_fre")
        self.gridLayout.addWidget(self.Start_fre, 2, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.Len_fre = QtWidgets.QDoubleSpinBox(self.widget)
        self.Len_fre.setMinimumSize(QtCore.QSize(200, 50))
        self.Len_fre.setMaximum(500.0)
        self.Len_fre.setSingleStep(0.001)
        self.Len_fre.setObjectName("Len_fre")
        self.gridLayout.addWidget(self.Len_fre, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.Stop_fre = QtWidgets.QDoubleSpinBox(self.widget)
        self.Stop_fre.setMinimumSize(QtCore.QSize(200, 50))
        self.Stop_fre.setMaximum(500.0)
        self.Stop_fre.setSingleStep(1.0)
        self.Stop_fre.setObjectName("Stop_fre")
        self.gridLayout.addWidget(self.Stop_fre, 4, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.Manual_input = QtWidgets.QPushButton(self.widget)
        self.Manual_input.setMinimumSize(QtCore.QSize(0, 50))
        self.Manual_input.setObjectName("Manual_input")
        self.verticalLayout.addWidget(self.Manual_input)
        self.Start_scan = QtWidgets.QPushButton(self.widget)
        self.Start_scan.setMinimumSize(QtCore.QSize(0, 50))
        self.Start_scan.setObjectName("Start_scan")
        self.verticalLayout.addWidget(self.Start_scan)
        self.Save = QtWidgets.QPushButton(self.widget)
        self.Save.setMinimumSize(QtCore.QSize(0, 50))
        self.Save.setObjectName("Save")
        self.verticalLayout.addWidget(self.Save)
        self.Plot_area.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "round time"))
        self.label_5.setText(_translate("MainWindow", "sleeping time"))
        self.label.setText(_translate("MainWindow", "start_fre"))
        self.label_3.setText(_translate("MainWindow", "length"))
        self.label_2.setText(_translate("MainWindow", "stop_fre"))
        self.Manual_input.setText(_translate("MainWindow", "manual input"))
        self.Start_scan.setText(_translate("MainWindow", "start scan"))
        self.Save.setText(_translate("MainWindow", "save"))

