# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18926\Desktop\qtsesigner\gui_test_07_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 290, 111, 41))
        self.label.setObjectName("label")
        self.pinbox_stoptime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_stoptime.setGeometry(QtCore.QRect(30, 400, 71, 22))
        self.pinbox_stoptime.setObjectName("pinbox_stoptime")
        self.pinbox_begintime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_begintime.setGeometry(QtCore.QRect(30, 370, 71, 22))
        self.pinbox_begintime.setObjectName("pinbox_begintime")
        self.pinbox_choose = QtWidgets.QSpinBox(self.centralwidget)
        self.pinbox_choose.setGeometry(QtCore.QRect(30, 340, 71, 22))
        self.pinbox_choose.setSuffix("")
        self.pinbox_choose.setMaximum(10)
        self.pinbox_choose.setObjectName("pinbox_choose")
        self.comboBox_starttime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_starttime.setGeometry(QtCore.QRect(110, 370, 87, 22))
        self.comboBox_starttime.setEditable(True)
        self.comboBox_starttime.setObjectName("comboBox_starttime")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_stoptime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stoptime.setGeometry(QtCore.QRect(110, 400, 87, 22))
        self.comboBox_stoptime.setEditable(True)
        self.comboBox_stoptime.setObjectName("comboBox_stoptime")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(30, 440, 93, 28))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(30, 470, 93, 28))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setGeometry(QtCore.QRect(30, 500, 191, 28))
        self.pushButton_show.setObjectName("pushButton_show")
        self.pushButton_runtimeline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runtimeline.setGeometry(QtCore.QRect(30, 530, 121, 28))
        self.pushButton_runtimeline.setObjectName("pushButton_runtimeline")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(30, 560, 711, 251))
        self.textEdit_log.setObjectName("textEdit_log")
        self.checkBox_DC1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC1.setGeometry(QtCore.QRect(170, 80, 51, 19))
        self.checkBox_DC1.setObjectName("checkBox_DC1")
        self.checkBox_DC2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC2.setGeometry(QtCore.QRect(300, 80, 51, 19))
        self.checkBox_DC2.setObjectName("checkBox_DC2")
        self.checkBox_DC3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC3.setGeometry(QtCore.QRect(450, 80, 51, 19))
        self.checkBox_DC3.setObjectName("checkBox_DC3")
        self.checkBox_DC4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC4.setGeometry(QtCore.QRect(610, 80, 51, 19))
        self.checkBox_DC4.setObjectName("checkBox_DC4")
        self.checkBox_DC5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC5.setGeometry(QtCore.QRect(790, 80, 51, 19))
        self.checkBox_DC5.setObjectName("checkBox_DC5")
        self.checkBox_DC6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC6.setGeometry(QtCore.QRect(960, 80, 51, 19))
        self.checkBox_DC6.setObjectName("checkBox_DC6")
        self.checkBox_DC7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC7.setGeometry(QtCore.QRect(170, 170, 51, 19))
        self.checkBox_DC7.setObjectName("checkBox_DC7")
        self.checkBox_DC8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC8.setGeometry(QtCore.QRect(300, 170, 51, 19))
        self.checkBox_DC8.setObjectName("checkBox_DC8")
        self.checkBox_DC9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC9.setGeometry(QtCore.QRect(450, 170, 51, 19))
        self.checkBox_DC9.setObjectName("checkBox_DC9")
        self.checkBox_DC10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC10.setGeometry(QtCore.QRect(610, 170, 71, 19))
        self.checkBox_DC10.setObjectName("checkBox_DC10")
        self.DCstate = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate.setGeometry(QtCore.QRect(170, 110, 51, 41))
        self.DCstate.setObjectName("DCstate")
        self.DCup = QtWidgets.QPushButton(self.centralwidget)
        self.DCup.setGeometry(QtCore.QRect(220, 110, 21, 21))
        self.DCup.setObjectName("DCup")
        self.DCdown = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown.setGeometry(QtCore.QRect(220, 130, 21, 21))
        self.DCdown.setText("")
        self.DCdown.setObjectName("DCdown")
        self.DCstate_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_2.setGeometry(QtCore.QRect(300, 110, 51, 41))
        self.DCstate_2.setObjectName("DCstate_2")
        self.DCup_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_2.setGeometry(QtCore.QRect(350, 110, 21, 21))
        self.DCup_2.setObjectName("DCup_2")
        self.DCdown_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_2.setGeometry(QtCore.QRect(350, 130, 21, 21))
        self.DCdown_2.setText("")
        self.DCdown_2.setObjectName("DCdown_2")
        self.DCstate_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_3.setGeometry(QtCore.QRect(450, 110, 51, 41))
        self.DCstate_3.setObjectName("DCstate_3")
        self.DCup_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_3.setGeometry(QtCore.QRect(500, 110, 21, 21))
        self.DCup_3.setObjectName("DCup_3")
        self.DCdown_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_3.setGeometry(QtCore.QRect(500, 130, 21, 21))
        self.DCdown_3.setText("")
        self.DCdown_3.setObjectName("DCdown_3")
        self.DCstate_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_4.setGeometry(QtCore.QRect(610, 110, 51, 41))
        self.DCstate_4.setObjectName("DCstate_4")
        self.DCup_4 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_4.setGeometry(QtCore.QRect(660, 110, 21, 21))
        self.DCup_4.setObjectName("DCup_4")
        self.DCdown_4 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_4.setGeometry(QtCore.QRect(660, 130, 21, 21))
        self.DCdown_4.setText("")
        self.DCdown_4.setObjectName("DCdown_4")
        self.DCstate_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_5.setGeometry(QtCore.QRect(790, 110, 51, 41))
        self.DCstate_5.setObjectName("DCstate_5")
        self.DCup_5 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_5.setGeometry(QtCore.QRect(840, 110, 21, 21))
        self.DCup_5.setObjectName("DCup_5")
        self.DCdown_5 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_5.setGeometry(QtCore.QRect(840, 130, 21, 21))
        self.DCdown_5.setText("")
        self.DCdown_5.setObjectName("DCdown_5")
        self.DCstate_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_6.setGeometry(QtCore.QRect(960, 110, 51, 41))
        self.DCstate_6.setObjectName("DCstate_6")
        self.DCup_6 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_6.setGeometry(QtCore.QRect(1010, 110, 21, 21))
        self.DCup_6.setObjectName("DCup_6")
        self.DCdown_6 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_6.setGeometry(QtCore.QRect(1010, 130, 21, 21))
        self.DCdown_6.setText("")
        self.DCdown_6.setObjectName("DCdown_6")
        self.DCstate_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_7.setGeometry(QtCore.QRect(170, 200, 51, 41))
        self.DCstate_7.setObjectName("DCstate_7")
        self.DCup_7 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_7.setGeometry(QtCore.QRect(220, 200, 21, 21))
        self.DCup_7.setObjectName("DCup_7")
        self.DCdown_7 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_7.setGeometry(QtCore.QRect(220, 220, 21, 21))
        self.DCdown_7.setText("")
        self.DCdown_7.setObjectName("DCdown_7")
        self.DCstate_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_8.setGeometry(QtCore.QRect(300, 200, 51, 41))
        self.DCstate_8.setObjectName("DCstate_8")
        self.DCup_8 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_8.setGeometry(QtCore.QRect(350, 200, 21, 21))
        self.DCup_8.setObjectName("DCup_8")
        self.DCdown_8 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_8.setGeometry(QtCore.QRect(350, 220, 21, 21))
        self.DCdown_8.setText("")
        self.DCdown_8.setObjectName("DCdown_8")
        self.DCstate_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_9.setGeometry(QtCore.QRect(450, 200, 51, 41))
        self.DCstate_9.setObjectName("DCstate_9")
        self.DCup_9 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_9.setGeometry(QtCore.QRect(500, 200, 21, 21))
        self.DCup_9.setObjectName("DCup_9")
        self.DCdown_9 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_9.setGeometry(QtCore.QRect(500, 220, 21, 21))
        self.DCdown_9.setText("")
        self.DCdown_9.setObjectName("DCdown_9")
        self.DCstate_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_10.setGeometry(QtCore.QRect(610, 200, 51, 41))
        self.DCstate_10.setObjectName("DCstate_10")
        self.DCup_10 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_10.setGeometry(QtCore.QRect(660, 200, 21, 21))
        self.DCup_10.setObjectName("DCup_10")
        self.DCdown_10 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_10.setGeometry(QtCore.QRect(660, 220, 21, 21))
        self.DCdown_10.setText("")
        self.DCdown_10.setObjectName("DCdown_10")
        self.DCup_sel = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_sel.setGeometry(QtCore.QRect(110, 130, 31, 31))
        self.DCup_sel.setObjectName("DCup_sel")
        self.DCdown_sel = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_sel.setGeometry(QtCore.QRect(110, 160, 31, 31))
        self.DCdown_sel.setText("")
        self.DCdown_sel.setObjectName("DCdown_sel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 71, 41))
        self.label_2.setObjectName("label_2")
        self.readall = QtWidgets.QPushButton(self.centralwidget)
        self.readall.setGeometry(QtCore.QRect(10, 190, 151, 41))
        self.readall.setObjectName("readall")
        self.DCdown_11 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_11.setGeometry(QtCore.QRect(840, 220, 21, 21))
        self.DCdown_11.setText("")
        self.DCdown_11.setObjectName("DCdown_11")
        self.checkBox_DC11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC11.setGeometry(QtCore.QRect(790, 170, 71, 19))
        self.checkBox_DC11.setObjectName("checkBox_DC11")
        self.DCstate_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_11.setGeometry(QtCore.QRect(790, 200, 51, 41))
        self.DCstate_11.setObjectName("DCstate_11")
        self.DCup_11 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_11.setGeometry(QtCore.QRect(840, 200, 21, 21))
        self.DCup_11.setObjectName("DCup_11")
        self.DCdown_12 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_12.setGeometry(QtCore.QRect(1010, 220, 21, 21))
        self.DCdown_12.setText("")
        self.DCdown_12.setObjectName("DCdown_12")
        self.checkBox_DC12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC12.setGeometry(QtCore.QRect(960, 170, 71, 19))
        self.checkBox_DC12.setObjectName("checkBox_DC12")
        self.DCstate_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_12.setGeometry(QtCore.QRect(960, 200, 51, 41))
        self.DCstate_12.setObjectName("DCstate_12")
        self.DCup_12 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_12.setGeometry(QtCore.QRect(1010, 200, 21, 21))
        self.DCup_12.setObjectName("DCup_12")
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_1.setGeometry(QtCore.QRect(240, 100, 51, 51))
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(370, 100, 51, 51))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(520, 100, 51, 51))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(680, 100, 51, 51))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(860, 100, 51, 51))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(1030, 100, 51, 51))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(240, 190, 51, 51))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(370, 190, 51, 51))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(520, 190, 51, 51))
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(680, 190, 51, 51))
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(860, 190, 51, 51))
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_12.setGeometry(QtCore.QRect(1030, 190, 51, 51))
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "timeline set"))
        self.pinbox_choose.setPrefix(_translate("MainWindow", "ttl"))
        self.comboBox_starttime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_starttime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_starttime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_starttime.setItemText(3, _translate("MainWindow", "ns"))
        self.comboBox_stoptime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_stoptime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_stoptime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_stoptime.setItemText(3, _translate("MainWindow", "ns"))
        self.pushButton_add.setText(_translate("MainWindow", "add"))
        self.pushButton_delete.setText(_translate("MainWindow", "delete"))
        self.pushButton_show.setText(_translate("MainWindow", "show current timeline"))
        self.pushButton_runtimeline.setText(_translate("MainWindow", "runtimeline"))
        self.checkBox_DC1.setText(_translate("MainWindow", "DC1"))
        self.checkBox_DC2.setText(_translate("MainWindow", "DC2"))
        self.checkBox_DC3.setText(_translate("MainWindow", "DC3"))
        self.checkBox_DC4.setText(_translate("MainWindow", "DC4"))
        self.checkBox_DC5.setText(_translate("MainWindow", "DC5"))
        self.checkBox_DC6.setText(_translate("MainWindow", "DC6"))
        self.checkBox_DC7.setText(_translate("MainWindow", "DC7"))
        self.checkBox_DC8.setText(_translate("MainWindow", "DC8"))
        self.checkBox_DC9.setText(_translate("MainWindow", "DC9"))
        self.checkBox_DC10.setText(_translate("MainWindow", "DC10"))
        self.DCup.setText(_translate("MainWindow", "^"))
        self.DCup_2.setText(_translate("MainWindow", "^"))
        self.DCup_3.setText(_translate("MainWindow", "^"))
        self.DCup_4.setText(_translate("MainWindow", "^"))
        self.DCup_5.setText(_translate("MainWindow", "^"))
        self.DCup_6.setText(_translate("MainWindow", "^"))
        self.DCup_7.setText(_translate("MainWindow", "^"))
        self.DCup_8.setText(_translate("MainWindow", "^"))
        self.DCup_9.setText(_translate("MainWindow", "^"))
        self.DCup_10.setText(_translate("MainWindow", "^"))
        self.DCup_sel.setText(_translate("MainWindow", "^"))
        self.label_2.setText(_translate("MainWindow", "selectDC"))
        self.readall.setText(_translate("MainWindow", "read manual input"))
        self.checkBox_DC11.setText(_translate("MainWindow", "DC11"))
        self.DCup_11.setText(_translate("MainWindow", "^"))
        self.checkBox_DC12.setText(_translate("MainWindow", "DC12"))
        self.DCup_12.setText(_translate("MainWindow", "^"))

