# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18926\Desktop\qtsesigner\DC_set_window20.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_DC_2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_2.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_2.setSizePolicy(sizePolicy)
        self.checkBox_DC_2.setObjectName("checkBox_DC_2")
        self.gridLayout.addWidget(self.checkBox_DC_2, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_1.sizePolicy().hasHeightForWidth())
        self.DCup_1.setSizePolicy(sizePolicy)
        self.DCup_1.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_1.setObjectName("DCup_1")
        self.gridLayout.addWidget(self.DCup_1, 0, 1, 1, 1)
        self.DCup_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_2.sizePolicy().hasHeightForWidth())
        self.DCup_2.setSizePolicy(sizePolicy)
        self.DCup_2.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_2.setObjectName("DCup_2")
        self.gridLayout.addWidget(self.DCup_2, 0, 4, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 0, 5, 2, 1)
        self.checkBox_DC_3 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_3.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_3.setSizePolicy(sizePolicy)
        self.checkBox_DC_3.setObjectName("checkBox_DC_3")
        self.gridLayout.addWidget(self.checkBox_DC_3, 0, 6, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_3.sizePolicy().hasHeightForWidth())
        self.DCup_3.setSizePolicy(sizePolicy)
        self.DCup_3.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_3.setObjectName("DCup_3")
        self.gridLayout.addWidget(self.DCup_3, 0, 7, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 0, 8, 2, 1)
        self.checkBox_DC_4 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_4.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_4.setSizePolicy(sizePolicy)
        self.checkBox_DC_4.setObjectName("checkBox_DC_4")
        self.gridLayout.addWidget(self.checkBox_DC_4, 0, 9, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_4.sizePolicy().hasHeightForWidth())
        self.DCup_4.setSizePolicy(sizePolicy)
        self.DCup_4.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_4.setObjectName("DCup_4")
        self.gridLayout.addWidget(self.DCup_4, 0, 10, 1, 1)
        self.checkBox_DC_1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_1.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_1.setSizePolicy(sizePolicy)
        self.checkBox_DC_1.setObjectName("checkBox_DC_1")
        self.gridLayout.addWidget(self.checkBox_DC_1, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_1.setSingleStep(0.01)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout.addWidget(self.doubleSpinBox_1, 0, 2, 2, 1)
        self.DCstate_5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_5.sizePolicy().hasHeightForWidth())
        self.DCstate_5.setSizePolicy(sizePolicy)
        self.DCstate_5.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_5.setObjectName("DCstate_5")
        self.gridLayout.addWidget(self.DCstate_5, 1, 12, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_6.sizePolicy().hasHeightForWidth())
        self.DCup_6.setSizePolicy(sizePolicy)
        self.DCup_6.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_6.setObjectName("DCup_6")
        self.gridLayout.addWidget(self.DCup_6, 0, 16, 1, 1)
        self.DCdown_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_5.sizePolicy().hasHeightForWidth())
        self.DCdown_5.setSizePolicy(sizePolicy)
        self.DCdown_5.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_5.setText("")
        self.DCdown_5.setObjectName("DCdown_5")
        self.gridLayout.addWidget(self.DCdown_5, 1, 13, 1, 1)
        self.DCdown_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_6.sizePolicy().hasHeightForWidth())
        self.DCdown_6.setSizePolicy(sizePolicy)
        self.DCdown_6.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_6.setText("")
        self.DCdown_6.setObjectName("DCdown_6")
        self.gridLayout.addWidget(self.DCdown_6, 1, 16, 1, 1)
        self.DCdown_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_1.sizePolicy().hasHeightForWidth())
        self.DCdown_1.setSizePolicy(sizePolicy)
        self.DCdown_1.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_1.setText("")
        self.DCdown_1.setObjectName("DCdown_1")
        self.gridLayout.addWidget(self.DCdown_1, 1, 1, 1, 1)
        self.DCstate_4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_4.sizePolicy().hasHeightForWidth())
        self.DCstate_4.setSizePolicy(sizePolicy)
        self.DCstate_4.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_4.setObjectName("DCstate_4")
        self.gridLayout.addWidget(self.DCstate_4, 1, 9, 1, 1, QtCore.Qt.AlignRight)
        self.DCstate_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_1.sizePolicy().hasHeightForWidth())
        self.DCstate_1.setSizePolicy(sizePolicy)
        self.DCstate_1.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_1.setObjectName("DCstate_1")
        self.gridLayout.addWidget(self.DCstate_1, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setSingleStep(0.01)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 0, 14, 2, 1)
        self.DCdown_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_3.sizePolicy().hasHeightForWidth())
        self.DCdown_3.setSizePolicy(sizePolicy)
        self.DCdown_3.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_3.setText("")
        self.DCdown_3.setObjectName("DCdown_3")
        self.gridLayout.addWidget(self.DCdown_3, 1, 7, 1, 1)
        self.DCdown_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_2.sizePolicy().hasHeightForWidth())
        self.DCdown_2.setSizePolicy(sizePolicy)
        self.DCdown_2.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_2.setText("")
        self.DCdown_2.setObjectName("DCdown_2")
        self.gridLayout.addWidget(self.DCdown_2, 1, 4, 1, 1)
        self.DCup_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_5.sizePolicy().hasHeightForWidth())
        self.DCup_5.setSizePolicy(sizePolicy)
        self.DCup_5.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_5.setObjectName("DCup_5")
        self.gridLayout.addWidget(self.DCup_5, 0, 13, 1, 1)
        self.DCstate_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_2.sizePolicy().hasHeightForWidth())
        self.DCstate_2.setSizePolicy(sizePolicy)
        self.DCstate_2.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_2.setObjectName("DCstate_2")
        self.gridLayout.addWidget(self.DCstate_2, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.checkBox_DC_5 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_5.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_5.setSizePolicy(sizePolicy)
        self.checkBox_DC_5.setObjectName("checkBox_DC_5")
        self.gridLayout.addWidget(self.checkBox_DC_5, 0, 12, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_4.sizePolicy().hasHeightForWidth())
        self.DCdown_4.setSizePolicy(sizePolicy)
        self.DCdown_4.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_4.setText("")
        self.DCdown_4.setObjectName("DCdown_4")
        self.gridLayout.addWidget(self.DCdown_4, 1, 10, 1, 1)
        self.DCstate_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_3.sizePolicy().hasHeightForWidth())
        self.DCstate_3.setSizePolicy(sizePolicy)
        self.DCstate_3.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_3.setObjectName("DCstate_3")
        self.gridLayout.addWidget(self.DCstate_3, 1, 6, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 0, 11, 2, 1)
        self.checkBox_DC_6 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_6.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_6.setSizePolicy(sizePolicy)
        self.checkBox_DC_6.setObjectName("checkBox_DC_6")
        self.gridLayout.addWidget(self.checkBox_DC_6, 0, 15, 1, 1, QtCore.Qt.AlignRight)
        self.DCstate_6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_6.sizePolicy().hasHeightForWidth())
        self.DCstate_6.setSizePolicy(sizePolicy)
        self.DCstate_6.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_6.setObjectName("DCstate_6")
        self.gridLayout.addWidget(self.DCstate_6, 1, 15, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_6.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_6.setSizePolicy(sizePolicy)
        self.doubleSpinBox_6.setSingleStep(0.01)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 0, 17, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.DCup_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_7.sizePolicy().hasHeightForWidth())
        self.DCup_7.setSizePolicy(sizePolicy)
        self.DCup_7.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_7.setObjectName("DCup_7")
        self.gridLayout_9.addWidget(self.DCup_7, 0, 1, 1, 1)
        self.DCdown_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_7.sizePolicy().hasHeightForWidth())
        self.DCdown_7.setSizePolicy(sizePolicy)
        self.DCdown_7.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_7.setText("")
        self.DCdown_7.setObjectName("DCdown_7")
        self.gridLayout_9.addWidget(self.DCdown_7, 1, 1, 1, 1)
        self.checkBox_DC_7 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_7.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_7.setSizePolicy(sizePolicy)
        self.checkBox_DC_7.setObjectName("checkBox_DC_7")
        self.gridLayout_9.addWidget(self.checkBox_DC_7, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCstate_7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_7.sizePolicy().hasHeightForWidth())
        self.DCstate_7.setSizePolicy(sizePolicy)
        self.DCstate_7.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_7.setObjectName("DCstate_7")
        self.gridLayout_9.addWidget(self.DCstate_7, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_7.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_7.setSizePolicy(sizePolicy)
        self.doubleSpinBox_7.setSingleStep(0.01)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_9.addWidget(self.doubleSpinBox_7, 0, 2, 2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_9)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.DCup_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_8.sizePolicy().hasHeightForWidth())
        self.DCup_8.setSizePolicy(sizePolicy)
        self.DCup_8.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_8.setObjectName("DCup_8")
        self.gridLayout_10.addWidget(self.DCup_8, 0, 1, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_8.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_8.setSizePolicy(sizePolicy)
        self.doubleSpinBox_8.setSingleStep(0.01)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_10.addWidget(self.doubleSpinBox_8, 0, 2, 2, 1)
        self.DCdown_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_8.sizePolicy().hasHeightForWidth())
        self.DCdown_8.setSizePolicy(sizePolicy)
        self.DCdown_8.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_8.setText("")
        self.DCdown_8.setObjectName("DCdown_8")
        self.gridLayout_10.addWidget(self.DCdown_8, 1, 1, 1, 1)
        self.DCstate_8 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_8.sizePolicy().hasHeightForWidth())
        self.DCstate_8.setSizePolicy(sizePolicy)
        self.DCstate_8.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_8.setObjectName("DCstate_8")
        self.gridLayout_10.addWidget(self.DCstate_8, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.checkBox_DC_8 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_8.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_8.setSizePolicy(sizePolicy)
        self.checkBox_DC_8.setObjectName("checkBox_DC_8")
        self.gridLayout_10.addWidget(self.checkBox_DC_8, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addLayout(self.gridLayout_10)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.checkBox_DC_9 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_9.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_9.setSizePolicy(sizePolicy)
        self.checkBox_DC_9.setObjectName("checkBox_DC_9")
        self.gridLayout_11.addWidget(self.checkBox_DC_9, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_9.sizePolicy().hasHeightForWidth())
        self.DCup_9.setSizePolicy(sizePolicy)
        self.DCup_9.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_9.setObjectName("DCup_9")
        self.gridLayout_11.addWidget(self.DCup_9, 0, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_9.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_9.setSizePolicy(sizePolicy)
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_11.addWidget(self.doubleSpinBox_9, 0, 2, 2, 1)
        self.DCdown_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_9.sizePolicy().hasHeightForWidth())
        self.DCdown_9.setSizePolicy(sizePolicy)
        self.DCdown_9.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_9.setText("")
        self.DCdown_9.setObjectName("DCdown_9")
        self.gridLayout_11.addWidget(self.DCdown_9, 1, 1, 1, 1)
        self.DCstate_9 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_9.sizePolicy().hasHeightForWidth())
        self.DCstate_9.setSizePolicy(sizePolicy)
        self.DCstate_9.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_9.setObjectName("DCstate_9")
        self.gridLayout_11.addWidget(self.DCstate_9, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addLayout(self.gridLayout_11)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_10.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_10.setSizePolicy(sizePolicy)
        self.doubleSpinBox_10.setSingleStep(0.01)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_12.addWidget(self.doubleSpinBox_10, 0, 2, 2, 1)
        self.checkBox_DC_10 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_10.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_10.setSizePolicy(sizePolicy)
        self.checkBox_DC_10.setObjectName("checkBox_DC_10")
        self.gridLayout_12.addWidget(self.checkBox_DC_10, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCstate_10 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_10.sizePolicy().hasHeightForWidth())
        self.DCstate_10.setSizePolicy(sizePolicy)
        self.DCstate_10.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_10.setObjectName("DCstate_10")
        self.gridLayout_12.addWidget(self.DCstate_10, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_10.sizePolicy().hasHeightForWidth())
        self.DCup_10.setSizePolicy(sizePolicy)
        self.DCup_10.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_10.setObjectName("DCup_10")
        self.gridLayout_12.addWidget(self.DCup_10, 0, 1, 1, 1)
        self.DCdown_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_10.sizePolicy().hasHeightForWidth())
        self.DCdown_10.setSizePolicy(sizePolicy)
        self.DCdown_10.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_10.setText("")
        self.DCdown_10.setObjectName("DCdown_10")
        self.gridLayout_12.addWidget(self.DCdown_10, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_12)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.DCdown_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_11.sizePolicy().hasHeightForWidth())
        self.DCdown_11.setSizePolicy(sizePolicy)
        self.DCdown_11.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_11.setText("")
        self.DCdown_11.setObjectName("DCdown_11")
        self.gridLayout_13.addWidget(self.DCdown_11, 1, 1, 1, 1)
        self.DCup_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_11.sizePolicy().hasHeightForWidth())
        self.DCup_11.setSizePolicy(sizePolicy)
        self.DCup_11.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_11.setObjectName("DCup_11")
        self.gridLayout_13.addWidget(self.DCup_11, 0, 1, 1, 1)
        self.DCstate_11 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_11.sizePolicy().hasHeightForWidth())
        self.DCstate_11.setSizePolicy(sizePolicy)
        self.DCstate_11.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_11.setObjectName("DCstate_11")
        self.gridLayout_13.addWidget(self.DCstate_11, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.checkBox_DC_11 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_11.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_11.setSizePolicy(sizePolicy)
        self.checkBox_DC_11.setObjectName("checkBox_DC_11")
        self.gridLayout_13.addWidget(self.checkBox_DC_11, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_11.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_11.setSizePolicy(sizePolicy)
        self.doubleSpinBox_11.setSingleStep(0.01)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_13.addWidget(self.doubleSpinBox_11, 0, 2, 2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_13)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.checkBox_DC_12 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_12.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_12.setSizePolicy(sizePolicy)
        self.checkBox_DC_12.setObjectName("checkBox_DC_12")
        self.gridLayout_14.addWidget(self.checkBox_DC_12, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_12.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_12.setSizePolicy(sizePolicy)
        self.doubleSpinBox_12.setSingleStep(0.01)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_14.addWidget(self.doubleSpinBox_12, 0, 2, 2, 1)
        self.DCstate_12 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_12.sizePolicy().hasHeightForWidth())
        self.DCstate_12.setSizePolicy(sizePolicy)
        self.DCstate_12.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_12.setObjectName("DCstate_12")
        self.gridLayout_14.addWidget(self.DCstate_12, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_12.sizePolicy().hasHeightForWidth())
        self.DCdown_12.setSizePolicy(sizePolicy)
        self.DCdown_12.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_12.setText("")
        self.DCdown_12.setObjectName("DCdown_12")
        self.gridLayout_14.addWidget(self.DCdown_12, 1, 1, 1, 1)
        self.DCup_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_12.sizePolicy().hasHeightForWidth())
        self.DCup_12.setSizePolicy(sizePolicy)
        self.DCup_12.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_12.setObjectName("DCup_12")
        self.gridLayout_14.addWidget(self.DCup_12, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_14)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_DC_13 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_13.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_13.setSizePolicy(sizePolicy)
        self.checkBox_DC_13.setObjectName("checkBox_DC_13")
        self.gridLayout_2.addWidget(self.checkBox_DC_13, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_13.sizePolicy().hasHeightForWidth())
        self.DCup_13.setSizePolicy(sizePolicy)
        self.DCup_13.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_13.setObjectName("DCup_13")
        self.gridLayout_2.addWidget(self.DCup_13, 0, 1, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_13.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_13.setSizePolicy(sizePolicy)
        self.doubleSpinBox_13.setSingleStep(0.01)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_2.addWidget(self.doubleSpinBox_13, 0, 2, 2, 1)
        self.checkBox_DC_14 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_14.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_14.setSizePolicy(sizePolicy)
        self.checkBox_DC_14.setObjectName("checkBox_DC_14")
        self.gridLayout_2.addWidget(self.checkBox_DC_14, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_14.sizePolicy().hasHeightForWidth())
        self.DCup_14.setSizePolicy(sizePolicy)
        self.DCup_14.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_14.setObjectName("DCup_14")
        self.gridLayout_2.addWidget(self.DCup_14, 0, 4, 1, 1)
        self.checkBox_DC_15 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_15.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_15.setSizePolicy(sizePolicy)
        self.checkBox_DC_15.setObjectName("checkBox_DC_15")
        self.gridLayout_2.addWidget(self.checkBox_DC_15, 0, 6, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_15.sizePolicy().hasHeightForWidth())
        self.DCup_15.setSizePolicy(sizePolicy)
        self.DCup_15.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_15.setObjectName("DCup_15")
        self.gridLayout_2.addWidget(self.DCup_15, 0, 7, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_15.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_15.setSizePolicy(sizePolicy)
        self.doubleSpinBox_15.setSingleStep(0.01)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout_2.addWidget(self.doubleSpinBox_15, 0, 8, 2, 1)
        self.checkBox_DC_16 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_16.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_16.setSizePolicy(sizePolicy)
        self.checkBox_DC_16.setObjectName("checkBox_DC_16")
        self.gridLayout_2.addWidget(self.checkBox_DC_16, 0, 9, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_16.sizePolicy().hasHeightForWidth())
        self.DCup_16.setSizePolicy(sizePolicy)
        self.DCup_16.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_16.setObjectName("DCup_16")
        self.gridLayout_2.addWidget(self.DCup_16, 0, 10, 1, 1)
        self.checkBox_DC_17 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_17.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_17.setSizePolicy(sizePolicy)
        self.checkBox_DC_17.setObjectName("checkBox_DC_17")
        self.gridLayout_2.addWidget(self.checkBox_DC_17, 0, 12, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_17.sizePolicy().hasHeightForWidth())
        self.DCup_17.setSizePolicy(sizePolicy)
        self.DCup_17.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_17.setObjectName("DCup_17")
        self.gridLayout_2.addWidget(self.DCup_17, 0, 13, 1, 1)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_17.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_17.setSizePolicy(sizePolicy)
        self.doubleSpinBox_17.setSingleStep(0.01)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.gridLayout_2.addWidget(self.doubleSpinBox_17, 0, 14, 2, 1)
        self.checkBox_DC_18 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_DC_18.sizePolicy().hasHeightForWidth())
        self.checkBox_DC_18.setSizePolicy(sizePolicy)
        self.checkBox_DC_18.setObjectName("checkBox_DC_18")
        self.gridLayout_2.addWidget(self.checkBox_DC_18, 0, 15, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_18.sizePolicy().hasHeightForWidth())
        self.DCup_18.setSizePolicy(sizePolicy)
        self.DCup_18.setMaximumSize(QtCore.QSize(40, 40))
        self.DCup_18.setObjectName("DCup_18")
        self.gridLayout_2.addWidget(self.DCup_18, 0, 16, 1, 1)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_18.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_18.setSizePolicy(sizePolicy)
        self.doubleSpinBox_18.setSingleStep(0.01)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.gridLayout_2.addWidget(self.doubleSpinBox_18, 0, 17, 2, 1)
        self.DCstate_13 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_13.sizePolicy().hasHeightForWidth())
        self.DCstate_13.setSizePolicy(sizePolicy)
        self.DCstate_13.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_13.setObjectName("DCstate_13")
        self.gridLayout_2.addWidget(self.DCstate_13, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_13.sizePolicy().hasHeightForWidth())
        self.DCdown_13.setSizePolicy(sizePolicy)
        self.DCdown_13.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_13.setText("")
        self.DCdown_13.setObjectName("DCdown_13")
        self.gridLayout_2.addWidget(self.DCdown_13, 1, 1, 1, 1)
        self.DCstate_14 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_14.sizePolicy().hasHeightForWidth())
        self.DCstate_14.setSizePolicy(sizePolicy)
        self.DCstate_14.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_14.setObjectName("DCstate_14")
        self.gridLayout_2.addWidget(self.DCstate_14, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_14.sizePolicy().hasHeightForWidth())
        self.DCdown_14.setSizePolicy(sizePolicy)
        self.DCdown_14.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_14.setText("")
        self.DCdown_14.setObjectName("DCdown_14")
        self.gridLayout_2.addWidget(self.DCdown_14, 1, 4, 1, 1)
        self.DCstate_15 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_15.sizePolicy().hasHeightForWidth())
        self.DCstate_15.setSizePolicy(sizePolicy)
        self.DCstate_15.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_15.setObjectName("DCstate_15")
        self.gridLayout_2.addWidget(self.DCstate_15, 1, 6, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_15.sizePolicy().hasHeightForWidth())
        self.DCdown_15.setSizePolicy(sizePolicy)
        self.DCdown_15.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_15.setText("")
        self.DCdown_15.setObjectName("DCdown_15")
        self.gridLayout_2.addWidget(self.DCdown_15, 1, 7, 1, 1)
        self.DCstate_16 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_16.sizePolicy().hasHeightForWidth())
        self.DCstate_16.setSizePolicy(sizePolicy)
        self.DCstate_16.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_16.setObjectName("DCstate_16")
        self.gridLayout_2.addWidget(self.DCstate_16, 1, 9, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_16.sizePolicy().hasHeightForWidth())
        self.DCdown_16.setSizePolicy(sizePolicy)
        self.DCdown_16.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_16.setText("")
        self.DCdown_16.setObjectName("DCdown_16")
        self.gridLayout_2.addWidget(self.DCdown_16, 1, 10, 1, 1)
        self.DCstate_17 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_17.sizePolicy().hasHeightForWidth())
        self.DCstate_17.setSizePolicy(sizePolicy)
        self.DCstate_17.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_17.setObjectName("DCstate_17")
        self.gridLayout_2.addWidget(self.DCstate_17, 1, 12, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_17.sizePolicy().hasHeightForWidth())
        self.DCdown_17.setSizePolicy(sizePolicy)
        self.DCdown_17.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_17.setText("")
        self.DCdown_17.setObjectName("DCdown_17")
        self.gridLayout_2.addWidget(self.DCdown_17, 1, 13, 1, 1)
        self.DCstate_18 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCstate_18.sizePolicy().hasHeightForWidth())
        self.DCstate_18.setSizePolicy(sizePolicy)
        self.DCstate_18.setMaximumSize(QtCore.QSize(60, 60))
        self.DCstate_18.setObjectName("DCstate_18")
        self.gridLayout_2.addWidget(self.DCstate_18, 1, 15, 1, 1, QtCore.Qt.AlignRight)
        self.DCdown_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_18.sizePolicy().hasHeightForWidth())
        self.DCdown_18.setSizePolicy(sizePolicy)
        self.DCdown_18.setMaximumSize(QtCore.QSize(40, 40))
        self.DCdown_18.setText("")
        self.DCdown_18.setObjectName("DCdown_18")
        self.gridLayout_2.addWidget(self.DCdown_18, 1, 16, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_14.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_14.setSizePolicy(sizePolicy)
        self.doubleSpinBox_14.setSingleStep(0.01)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout_2.addWidget(self.doubleSpinBox_14, 0, 5, 2, 1)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_16.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_16.setSizePolicy(sizePolicy)
        self.doubleSpinBox_16.setSingleStep(0.01)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.gridLayout_2.addWidget(self.doubleSpinBox_16, 0, 11, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.readall = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readall.sizePolicy().hasHeightForWidth())
        self.readall.setSizePolicy(sizePolicy)
        self.readall.setMaximumSize(QtCore.QSize(200, 40))
        self.readall.setObjectName("readall")
        self.gridLayout_19.addWidget(self.readall, 1, 0, 1, 1)
        self.DCdown_sel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCdown_sel.sizePolicy().hasHeightForWidth())
        self.DCdown_sel.setSizePolicy(sizePolicy)
        self.DCdown_sel.setMaximumSize(QtCore.QSize(200, 40))
        self.DCdown_sel.setText("")
        self.DCdown_sel.setObjectName("DCdown_sel")
        self.gridLayout_19.addWidget(self.DCdown_sel, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        self.label_2.setObjectName("label_2")
        self.gridLayout_19.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.DCup_sel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCup_sel.sizePolicy().hasHeightForWidth())
        self.DCup_sel.setSizePolicy(sizePolicy)
        self.DCup_sel.setMaximumSize(QtCore.QSize(200, 40))
        self.DCup_sel.setObjectName("DCup_sel")
        self.gridLayout_19.addWidget(self.DCup_sel, 0, 1, 1, 1)
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setObjectName("textEdit_log")
        self.gridLayout_19.addWidget(self.textEdit_log, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_19)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_DC_2.setText(_translate("MainWindow", "DC2"))
        self.DCup_1.setText(_translate("MainWindow", "^"))
        self.DCup_2.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_3.setText(_translate("MainWindow", "DC3"))
        self.DCup_3.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_4.setText(_translate("MainWindow", "DC4"))
        self.DCup_4.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_1.setText(_translate("MainWindow", "DC1"))
        self.DCup_6.setText(_translate("MainWindow", "^"))
        self.DCup_5.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_5.setText(_translate("MainWindow", "DC5"))
        self.checkBox_DC_6.setText(_translate("MainWindow", "DC6"))
        self.DCup_7.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_7.setText(_translate("MainWindow", "DC7"))
        self.DCup_8.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_8.setText(_translate("MainWindow", "DC8"))
        self.checkBox_DC_9.setText(_translate("MainWindow", "DC9"))
        self.DCup_9.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_10.setText(_translate("MainWindow", "DC10"))
        self.DCup_10.setText(_translate("MainWindow", "^"))
        self.DCup_11.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_11.setText(_translate("MainWindow", "DC11"))
        self.checkBox_DC_12.setText(_translate("MainWindow", "DC12"))
        self.DCup_12.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_13.setText(_translate("MainWindow", "DC13"))
        self.DCup_13.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_14.setText(_translate("MainWindow", "DC14"))
        self.DCup_14.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_15.setText(_translate("MainWindow", "DC15"))
        self.DCup_15.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_16.setText(_translate("MainWindow", "DC16"))
        self.DCup_16.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_17.setText(_translate("MainWindow", "DC17"))
        self.DCup_17.setText(_translate("MainWindow", "^"))
        self.checkBox_DC_18.setText(_translate("MainWindow", "DC18"))
        self.DCup_18.setText(_translate("MainWindow", "^"))
        self.readall.setText(_translate("MainWindow", "read manual input"))
        self.label_2.setText(_translate("MainWindow", "selectDC"))
        self.DCup_sel.setText(_translate("MainWindow", "^"))

