# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18926\Desktop\qtsesigner\DC_set_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(50, 480, 711, 251))
        self.textEdit_log.setObjectName("textEdit_log")
        self.checkBox_DC1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC1.setGeometry(QtCore.QRect(90, 50, 51, 19))
        self.checkBox_DC1.setObjectName("checkBox_DC1")
        self.checkBox_DC2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC2.setGeometry(QtCore.QRect(220, 50, 51, 19))
        self.checkBox_DC2.setObjectName("checkBox_DC2")
        self.checkBox_DC3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC3.setGeometry(QtCore.QRect(370, 50, 51, 19))
        self.checkBox_DC3.setObjectName("checkBox_DC3")
        self.checkBox_DC4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC4.setGeometry(QtCore.QRect(530, 50, 51, 19))
        self.checkBox_DC4.setObjectName("checkBox_DC4")
        self.checkBox_DC5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC5.setGeometry(QtCore.QRect(710, 50, 51, 19))
        self.checkBox_DC5.setObjectName("checkBox_DC5")
        self.checkBox_DC6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC6.setGeometry(QtCore.QRect(880, 50, 51, 19))
        self.checkBox_DC6.setObjectName("checkBox_DC6")
        self.checkBox_DC7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC7.setGeometry(QtCore.QRect(90, 140, 51, 19))
        self.checkBox_DC7.setObjectName("checkBox_DC7")
        self.checkBox_DC8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC8.setGeometry(QtCore.QRect(220, 140, 51, 19))
        self.checkBox_DC8.setObjectName("checkBox_DC8")
        self.checkBox_DC9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC9.setGeometry(QtCore.QRect(370, 140, 51, 19))
        self.checkBox_DC9.setObjectName("checkBox_DC9")
        self.checkBox_DC10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC10.setGeometry(QtCore.QRect(530, 140, 71, 19))
        self.checkBox_DC10.setObjectName("checkBox_DC10")
        self.DCstate_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_1.setGeometry(QtCore.QRect(90, 80, 51, 41))
        self.DCstate_1.setObjectName("DCstate_1")
        self.DCup_1 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_1.setGeometry(QtCore.QRect(140, 80, 21, 21))
        self.DCup_1.setObjectName("DCup_1")
        self.DCdown_1 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_1.setGeometry(QtCore.QRect(140, 100, 21, 21))
        self.DCdown_1.setText("")
        self.DCdown_1.setObjectName("DCdown_1")
        self.DCstate_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_2.setGeometry(QtCore.QRect(220, 80, 51, 41))
        self.DCstate_2.setObjectName("DCstate_2")
        self.DCup_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_2.setGeometry(QtCore.QRect(270, 80, 21, 21))
        self.DCup_2.setObjectName("DCup_2")
        self.DCdown_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_2.setGeometry(QtCore.QRect(270, 100, 21, 21))
        self.DCdown_2.setText("")
        self.DCdown_2.setObjectName("DCdown_2")
        self.DCstate_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_3.setGeometry(QtCore.QRect(370, 80, 51, 41))
        self.DCstate_3.setObjectName("DCstate_3")
        self.DCup_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_3.setGeometry(QtCore.QRect(420, 80, 21, 21))
        self.DCup_3.setObjectName("DCup_3")
        self.DCdown_3 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_3.setGeometry(QtCore.QRect(420, 100, 21, 21))
        self.DCdown_3.setText("")
        self.DCdown_3.setObjectName("DCdown_3")
        self.DCstate_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_4.setGeometry(QtCore.QRect(530, 80, 51, 41))
        self.DCstate_4.setObjectName("DCstate_4")
        self.DCup_4 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_4.setGeometry(QtCore.QRect(580, 80, 21, 21))
        self.DCup_4.setObjectName("DCup_4")
        self.DCdown_4 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_4.setGeometry(QtCore.QRect(580, 100, 21, 21))
        self.DCdown_4.setText("")
        self.DCdown_4.setObjectName("DCdown_4")
        self.DCstate_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_5.setGeometry(QtCore.QRect(710, 80, 51, 41))
        self.DCstate_5.setObjectName("DCstate_5")
        self.DCup_5 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_5.setGeometry(QtCore.QRect(760, 80, 21, 21))
        self.DCup_5.setObjectName("DCup_5")
        self.DCdown_5 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_5.setGeometry(QtCore.QRect(760, 100, 21, 21))
        self.DCdown_5.setText("")
        self.DCdown_5.setObjectName("DCdown_5")
        self.DCstate_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_6.setGeometry(QtCore.QRect(880, 80, 51, 41))
        self.DCstate_6.setObjectName("DCstate_6")
        self.DCup_6 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_6.setGeometry(QtCore.QRect(930, 80, 21, 21))
        self.DCup_6.setObjectName("DCup_6")
        self.DCdown_6 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_6.setGeometry(QtCore.QRect(930, 100, 21, 21))
        self.DCdown_6.setText("")
        self.DCdown_6.setObjectName("DCdown_6")
        self.DCstate_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_7.setGeometry(QtCore.QRect(90, 170, 51, 41))
        self.DCstate_7.setObjectName("DCstate_7")
        self.DCup_7 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_7.setGeometry(QtCore.QRect(140, 170, 21, 21))
        self.DCup_7.setObjectName("DCup_7")
        self.DCdown_7 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_7.setGeometry(QtCore.QRect(140, 190, 21, 21))
        self.DCdown_7.setText("")
        self.DCdown_7.setObjectName("DCdown_7")
        self.DCstate_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_8.setGeometry(QtCore.QRect(220, 170, 51, 41))
        self.DCstate_8.setObjectName("DCstate_8")
        self.DCup_8 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_8.setGeometry(QtCore.QRect(270, 170, 21, 21))
        self.DCup_8.setObjectName("DCup_8")
        self.DCdown_8 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_8.setGeometry(QtCore.QRect(270, 190, 21, 21))
        self.DCdown_8.setText("")
        self.DCdown_8.setObjectName("DCdown_8")
        self.DCstate_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_9.setGeometry(QtCore.QRect(370, 170, 51, 41))
        self.DCstate_9.setObjectName("DCstate_9")
        self.DCup_9 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_9.setGeometry(QtCore.QRect(420, 170, 21, 21))
        self.DCup_9.setObjectName("DCup_9")
        self.DCdown_9 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_9.setGeometry(QtCore.QRect(420, 190, 21, 21))
        self.DCdown_9.setText("")
        self.DCdown_9.setObjectName("DCdown_9")
        self.DCstate_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_10.setGeometry(QtCore.QRect(530, 170, 51, 41))
        self.DCstate_10.setObjectName("DCstate_10")
        self.DCup_10 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_10.setGeometry(QtCore.QRect(580, 170, 21, 21))
        self.DCup_10.setObjectName("DCup_10")
        self.DCdown_10 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_10.setGeometry(QtCore.QRect(580, 190, 21, 21))
        self.DCdown_10.setText("")
        self.DCdown_10.setObjectName("DCdown_10")
        self.DCup_sel = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_sel.setGeometry(QtCore.QRect(110, 270, 31, 31))
        self.DCup_sel.setObjectName("DCup_sel")
        self.DCdown_sel = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_sel.setGeometry(QtCore.QRect(110, 300, 31, 31))
        self.DCdown_sel.setText("")
        self.DCdown_sel.setObjectName("DCdown_sel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 280, 71, 41))
        self.label_2.setObjectName("label_2")
        self.readall = QtWidgets.QPushButton(self.centralwidget)
        self.readall.setGeometry(QtCore.QRect(10, 330, 151, 41))
        self.readall.setObjectName("readall")
        self.DCdown_11 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_11.setGeometry(QtCore.QRect(760, 190, 21, 21))
        self.DCdown_11.setText("")
        self.DCdown_11.setObjectName("DCdown_11")
        self.checkBox_DC11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC11.setGeometry(QtCore.QRect(710, 140, 71, 19))
        self.checkBox_DC11.setObjectName("checkBox_DC11")
        self.DCstate_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_11.setGeometry(QtCore.QRect(710, 170, 51, 41))
        self.DCstate_11.setObjectName("DCstate_11")
        self.DCup_11 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_11.setGeometry(QtCore.QRect(760, 170, 21, 21))
        self.DCup_11.setObjectName("DCup_11")
        self.DCdown_12 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_12.setGeometry(QtCore.QRect(930, 190, 21, 21))
        self.DCdown_12.setText("")
        self.DCdown_12.setObjectName("DCdown_12")
        self.checkBox_DC12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC12.setGeometry(QtCore.QRect(880, 140, 71, 19))
        self.checkBox_DC12.setObjectName("checkBox_DC12")
        self.DCstate_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_12.setGeometry(QtCore.QRect(880, 170, 51, 41))
        self.DCstate_12.setObjectName("DCstate_12")
        self.DCup_12 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_12.setGeometry(QtCore.QRect(930, 170, 21, 21))
        self.DCup_12.setObjectName("DCup_12")
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_1.setGeometry(QtCore.QRect(160, 70, 51, 51))
        self.doubleSpinBox_1.setSingleStep(0.01)
        self.doubleSpinBox_1.setProperty("value", 0.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(290, 70, 51, 51))
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(440, 70, 51, 51))
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(600, 70, 51, 51))
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(780, 70, 51, 51))
        self.doubleSpinBox_5.setSingleStep(0.01)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(950, 70, 51, 51))
        self.doubleSpinBox_6.setSingleStep(0.01)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(160, 160, 51, 51))
        self.doubleSpinBox_7.setSingleStep(0.01)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(290, 160, 51, 51))
        self.doubleSpinBox_8.setSingleStep(0.01)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(440, 160, 51, 51))
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(600, 160, 51, 51))
        self.doubleSpinBox_10.setSingleStep(0.01)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(780, 160, 51, 51))
        self.doubleSpinBox_11.setSingleStep(0.01)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_12.setGeometry(QtCore.QRect(950, 160, 51, 51))
        self.doubleSpinBox_12.setSingleStep(0.01)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.DCstate_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_13.setGeometry(QtCore.QRect(340, 280, 51, 41))
        self.DCstate_13.setObjectName("DCstate_13")
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_13.setGeometry(QtCore.QRect(410, 270, 51, 51))
        self.doubleSpinBox_13.setSingleStep(0.01)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.DCstate_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_14.setGeometry(QtCore.QRect(510, 280, 51, 41))
        self.DCstate_14.setObjectName("DCstate_14")
        self.DCdown_13 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_13.setGeometry(QtCore.QRect(390, 300, 21, 21))
        self.DCdown_13.setText("")
        self.DCdown_13.setObjectName("DCdown_13")
        self.DCup_13 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_13.setGeometry(QtCore.QRect(390, 280, 21, 21))
        self.DCup_13.setObjectName("DCup_13")
        self.DCup_14 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_14.setGeometry(QtCore.QRect(560, 280, 21, 21))
        self.DCup_14.setObjectName("DCup_14")
        self.DCup_15 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_15.setGeometry(QtCore.QRect(390, 370, 21, 21))
        self.DCup_15.setObjectName("DCup_15")
        self.DCdown_14 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_14.setGeometry(QtCore.QRect(560, 300, 21, 21))
        self.DCdown_14.setText("")
        self.DCdown_14.setObjectName("DCdown_14")
        self.DCup_16 = QtWidgets.QPushButton(self.centralwidget)
        self.DCup_16.setGeometry(QtCore.QRect(560, 370, 21, 21))
        self.DCup_16.setObjectName("DCup_16")
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_14.setGeometry(QtCore.QRect(580, 270, 51, 51))
        self.doubleSpinBox_14.setSingleStep(0.01)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.DCstate_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_15.setGeometry(QtCore.QRect(340, 370, 51, 41))
        self.DCstate_15.setObjectName("DCstate_15")
        self.checkBox_DC14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC14.setGeometry(QtCore.QRect(510, 250, 71, 19))
        self.checkBox_DC14.setObjectName("checkBox_DC14")
        self.checkBox_DC16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC16.setGeometry(QtCore.QRect(510, 340, 71, 19))
        self.checkBox_DC16.setObjectName("checkBox_DC16")
        self.checkBox_DC13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC13.setGeometry(QtCore.QRect(340, 250, 61, 19))
        self.checkBox_DC13.setObjectName("checkBox_DC13")
        self.checkBox_DC15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DC15.setGeometry(QtCore.QRect(340, 340, 71, 19))
        self.checkBox_DC15.setObjectName("checkBox_DC15")
        self.DCstate_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.DCstate_16.setGeometry(QtCore.QRect(510, 370, 51, 41))
        self.DCstate_16.setObjectName("DCstate_16")
        self.DCdown_15 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_15.setGeometry(QtCore.QRect(390, 390, 21, 21))
        self.DCdown_15.setText("")
        self.DCdown_15.setObjectName("DCdown_15")
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_15.setGeometry(QtCore.QRect(410, 360, 51, 51))
        self.doubleSpinBox_15.setSingleStep(0.01)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.DCdown_16 = QtWidgets.QPushButton(self.centralwidget)
        self.DCdown_16.setGeometry(QtCore.QRect(560, 390, 21, 21))
        self.DCdown_16.setText("")
        self.DCdown_16.setObjectName("DCdown_16")
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_16.setGeometry(QtCore.QRect(580, 360, 51, 51))
        self.doubleSpinBox_16.setSingleStep(0.01)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_DC1.setText(_translate("MainWindow", "DC1"))
        self.checkBox_DC2.setText(_translate("MainWindow", "DC2"))
        self.checkBox_DC3.setText(_translate("MainWindow", "DC3"))
        self.checkBox_DC4.setText(_translate("MainWindow", "DC4"))
        self.checkBox_DC5.setText(_translate("MainWindow", "DC5"))
        self.checkBox_DC6.setText(_translate("MainWindow", "DC6"))
        self.checkBox_DC7.setText(_translate("MainWindow", "DC7"))
        self.checkBox_DC8.setText(_translate("MainWindow", "DC8"))
        self.checkBox_DC9.setText(_translate("MainWindow", "DC9"))
        self.checkBox_DC10.setText(_translate("MainWindow", "DC10"))
        self.DCup_1.setText(_translate("MainWindow", "^"))
        self.DCup_2.setText(_translate("MainWindow", "^"))
        self.DCup_3.setText(_translate("MainWindow", "^"))
        self.DCup_4.setText(_translate("MainWindow", "^"))
        self.DCup_5.setText(_translate("MainWindow", "^"))
        self.DCup_6.setText(_translate("MainWindow", "^"))
        self.DCup_7.setText(_translate("MainWindow", "^"))
        self.DCup_8.setText(_translate("MainWindow", "^"))
        self.DCup_9.setText(_translate("MainWindow", "^"))
        self.DCup_10.setText(_translate("MainWindow", "^"))
        self.DCup_sel.setText(_translate("MainWindow", "^"))
        self.label_2.setText(_translate("MainWindow", "selectDC"))
        self.readall.setText(_translate("MainWindow", "read manual input"))
        self.checkBox_DC11.setText(_translate("MainWindow", "DC11"))
        self.DCup_11.setText(_translate("MainWindow", "^"))
        self.checkBox_DC12.setText(_translate("MainWindow", "DC12"))
        self.DCup_12.setText(_translate("MainWindow", "^"))
        self.DCup_13.setText(_translate("MainWindow", "^"))
        self.DCup_14.setText(_translate("MainWindow", "^"))
        self.DCup_15.setText(_translate("MainWindow", "^"))
        self.DCup_16.setText(_translate("MainWindow", "^"))
        self.checkBox_DC14.setText(_translate("MainWindow", "DC14"))
        self.checkBox_DC16.setText(_translate("MainWindow", "DC16"))
        self.checkBox_DC13.setText(_translate("MainWindow", "DC13"))
        self.checkBox_DC15.setText(_translate("MainWindow", "DC15"))

