# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18926\Desktop\qtsesigner\timeline_set_gui20_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1430, 936)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 111, 41))
        self.label.setObjectName("label")
        self.pinbox_stoptime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_stoptime.setGeometry(QtCore.QRect(70, 200, 181, 91))
        self.pinbox_stoptime.setMaximum(1001.0)
        self.pinbox_stoptime.setObjectName("pinbox_stoptime")
        self.pinbox_begintime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_begintime.setGeometry(QtCore.QRect(70, 120, 181, 81))
        self.pinbox_begintime.setMaximum(1001.0)
        self.pinbox_begintime.setObjectName("pinbox_begintime")
        self.pinbox_choose = QtWidgets.QSpinBox(self.centralwidget)
        self.pinbox_choose.setGeometry(QtCore.QRect(70, 40, 181, 81))
        self.pinbox_choose.setSuffix("")
        self.pinbox_choose.setMaximum(10)
        self.pinbox_choose.setObjectName("pinbox_choose")
        self.comboBox_starttime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_starttime.setGeometry(QtCore.QRect(250, 120, 81, 61))
        self.comboBox_starttime.setEditable(True)
        self.comboBox_starttime.setObjectName("comboBox_starttime")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_stoptime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stoptime.setGeometry(QtCore.QRect(250, 200, 81, 61))
        self.comboBox_stoptime.setEditable(True)
        self.comboBox_stoptime.setObjectName("comboBox_stoptime")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(70, 290, 101, 51))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(70, 340, 101, 51))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setGeometry(QtCore.QRect(70, 390, 191, 61))
        self.pushButton_show.setObjectName("pushButton_show")
        self.pushButton_runtimeline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runtimeline.setGeometry(QtCore.QRect(140, 450, 241, 71))
        self.pushButton_runtimeline.setObjectName("pushButton_runtimeline")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(70, 520, 511, 251))
        self.textEdit_log.setObjectName("textEdit_log")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 240, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 780, 331, 16))
        self.label_4.setObjectName("label_4")
        self.add_sel = QtWidgets.QPushButton(self.centralwidget)
        self.add_sel.setGeometry(QtCore.QRect(260, 270, 261, 91))
        self.add_sel.setObjectName("add_sel")
        self.del_sel = QtWidgets.QPushButton(self.centralwidget)
        self.del_sel.setGeometry(QtCore.QRect(260, 360, 261, 91))
        self.del_sel.setObjectName("del_sel")
        self.add_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.add_posi.setGeometry(QtCore.QRect(520, 270, 121, 91))
        self.add_posi.setObjectName("add_posi")
        self.dele_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.dele_posi.setGeometry(QtCore.QRect(520, 360, 121, 91))
        self.dele_posi.setObjectName("dele_posi")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 490, 91, 31))
        self.label_5.setObjectName("label_5")
        self.textEdit_timeline = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_timeline.setGeometry(QtCore.QRect(790, 80, 441, 701))
        self.textEdit_timeline.setObjectName("textEdit_timeline")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 60, 72, 15))
        self.label_6.setObjectName("label_6")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(702, 80, 91, 91))
        self.load.setObjectName("load")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(700, 170, 93, 91))
        self.save.setObjectName("save")
        self.load_modual = QtWidgets.QPushButton(self.centralwidget)
        self.load_modual.setGeometry(QtCore.QRect(700, 320, 93, 101))
        self.load_modual.setObjectName("load_modual")
        self.pinbox_delaytime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_delaytime.setGeometry(QtCore.QRect(700, 420, 91, 91))
        self.pinbox_delaytime.setMaximum(1001.0)
        self.pinbox_delaytime.setObjectName("pinbox_delaytime")
        self.comboBox_delaytime_unit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_delaytime_unit.setGeometry(QtCore.QRect(700, 510, 91, 61))
        self.comboBox_delaytime_unit.setEditable(True)
        self.comboBox_delaytime_unit.setObjectName("comboBox_delaytime_unit")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.ord_time = QtWidgets.QPushButton(self.centralwidget)
        self.ord_time.setGeometry(QtCore.QRect(700, 610, 93, 81))
        self.ord_time.setObjectName("ord_time")
        self.mod_view = QtWidgets.QPushButton(self.centralwidget)
        self.mod_view.setGeometry(QtCore.QRect(700, 690, 93, 91))
        self.mod_view.setObjectName("mod_view")
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(1230, 80, 93, 101))
        self.update.setObjectName("update")
        self.open_monitor = QtWidgets.QPushButton(self.centralwidget)
        self.open_monitor.setGeometry(QtCore.QRect(420, 90, 111, 71))
        self.open_monitor.setObjectName("open_monitor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "timeline set"))
        self.pinbox_choose.setPrefix(_translate("MainWindow", "ttl"))
        self.comboBox_starttime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_starttime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_starttime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_starttime.setItemText(3, _translate("MainWindow", "ns"))
        self.comboBox_stoptime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_stoptime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_stoptime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_stoptime.setItemText(3, _translate("MainWindow", "ns"))
        self.pushButton_add.setText(_translate("MainWindow", "add"))
        self.pushButton_delete.setText(_translate("MainWindow", "delete"))
        self.pushButton_show.setText(_translate("MainWindow", "show current timeline"))
        self.pushButton_runtimeline.setText(_translate("MainWindow", "add timeline to data_set"))
        self.label_2.setText(_translate("MainWindow", "starttime"))
        self.label_3.setText(_translate("MainWindow", "stoptime"))
        self.label_4.setText(_translate("MainWindow", "delete the initial set at the very first"))
        self.add_sel.setText(_translate("MainWindow", "add at select position"))
        self.del_sel.setText(_translate("MainWindow", "delete after select position"))
        self.label_5.setText(_translate("MainWindow", "log"))
        self.label_6.setText(_translate("MainWindow", "timeline"))
        self.load.setText(_translate("MainWindow", "load"))
        self.save.setText(_translate("MainWindow", "save"))
        self.load_modual.setText(_translate("MainWindow", "add modual"))
        self.comboBox_delaytime_unit.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_delaytime_unit.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_delaytime_unit.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_delaytime_unit.setItemText(3, _translate("MainWindow", "ns"))
        self.ord_time.setText(_translate("MainWindow", "ord_time"))
        self.mod_view.setText(_translate("MainWindow", "mod_view"))
        self.update.setText(_translate("MainWindow", "update"))
        self.open_monitor.setText(_translate("MainWindow", "open monitor"))

