# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18926\Desktop\qtsesigner\gui_test_09_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 111, 41))
        self.label.setObjectName("label")
        self.pinbox_stoptime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_stoptime.setGeometry(QtCore.QRect(170, 200, 181, 91))
        self.pinbox_stoptime.setObjectName("pinbox_stoptime")
        self.pinbox_begintime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_begintime.setGeometry(QtCore.QRect(170, 120, 181, 81))
        self.pinbox_begintime.setObjectName("pinbox_begintime")
        self.pinbox_choose = QtWidgets.QSpinBox(self.centralwidget)
        self.pinbox_choose.setGeometry(QtCore.QRect(170, 40, 181, 81))
        self.pinbox_choose.setSuffix("")
        self.pinbox_choose.setMaximum(10)
        self.pinbox_choose.setObjectName("pinbox_choose")
        self.comboBox_starttime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_starttime.setGeometry(QtCore.QRect(350, 120, 81, 61))
        self.comboBox_starttime.setEditable(True)
        self.comboBox_starttime.setObjectName("comboBox_starttime")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_stoptime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stoptime.setGeometry(QtCore.QRect(350, 200, 81, 61))
        self.comboBox_stoptime.setEditable(True)
        self.comboBox_stoptime.setObjectName("comboBox_stoptime")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(170, 290, 101, 51))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(170, 340, 101, 51))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setGeometry(QtCore.QRect(170, 390, 191, 61))
        self.pushButton_show.setObjectName("pushButton_show")
        self.pushButton_runtimeline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runtimeline.setGeometry(QtCore.QRect(610, 70, 161, 101))
        self.pushButton_runtimeline.setObjectName("pushButton_runtimeline")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(170, 450, 711, 251))
        self.textEdit_log.setObjectName("textEdit_log")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 170, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 710, 471, 16))
        self.label_4.setObjectName("label_4")
        self.add_sel = QtWidgets.QPushButton(self.centralwidget)
        self.add_sel.setGeometry(QtCore.QRect(440, 260, 261, 91))
        self.add_sel.setObjectName("add_sel")
        self.del_sel = QtWidgets.QPushButton(self.centralwidget)
        self.del_sel.setGeometry(QtCore.QRect(440, 350, 261, 91))
        self.del_sel.setObjectName("del_sel")
        self.add_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.add_posi.setGeometry(QtCore.QRect(700, 260, 161, 91))
        self.add_posi.setObjectName("add_posi")
        self.dele_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.dele_posi.setGeometry(QtCore.QRect(700, 350, 161, 91))
        self.dele_posi.setObjectName("dele_posi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "timeline set"))
        self.pinbox_choose.setPrefix(_translate("MainWindow", "ttl"))
        self.comboBox_starttime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_starttime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_starttime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_starttime.setItemText(3, _translate("MainWindow", "ns"))
        self.comboBox_stoptime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_stoptime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_stoptime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_stoptime.setItemText(3, _translate("MainWindow", "ns"))
        self.pushButton_add.setText(_translate("MainWindow", "add"))
        self.pushButton_delete.setText(_translate("MainWindow", "delete"))
        self.pushButton_show.setText(_translate("MainWindow", "show current timeline"))
        self.pushButton_runtimeline.setText(_translate("MainWindow", "runtimeline"))
        self.label_2.setText(_translate("MainWindow", "starttime"))
        self.label_3.setText(_translate("MainWindow", "stoptime"))
        self.label_4.setText(_translate("MainWindow", "delete the initial set at the very first"))
        self.add_sel.setText(_translate("MainWindow", "add at select position"))
        self.del_sel.setText(_translate("MainWindow", "delete after select position"))

