# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\program\qtsesigner\timeline_set_gui30_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 885)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_stoptime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stoptime.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBox_stoptime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_stoptime.setEditable(True)
        self.comboBox_stoptime.setObjectName("comboBox_stoptime")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.comboBox_stoptime.addItem("")
        self.gridLayout.addWidget(self.comboBox_stoptime, 2, 2, 1, 1)
        self.comboBox_starttime = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_starttime.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBox_starttime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_starttime.setEditable(True)
        self.comboBox_starttime.setObjectName("comboBox_starttime")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.comboBox_starttime.addItem("")
        self.gridLayout.addWidget(self.comboBox_starttime, 1, 2, 1, 1)
        self.pinbox_stoptime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_stoptime.setMinimumSize(QtCore.QSize(0, 70))
        self.pinbox_stoptime.setDecimals(5)
        self.pinbox_stoptime.setMaximum(9999.0)
        self.pinbox_stoptime.setObjectName("pinbox_stoptime")
        self.gridLayout.addWidget(self.pinbox_stoptime, 2, 1, 1, 1)
        self.pinbox_begintime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_begintime.setMinimumSize(QtCore.QSize(0, 70))
        self.pinbox_begintime.setDecimals(4)
        self.pinbox_begintime.setMaximum(9999.0)
        self.pinbox_begintime.setObjectName("pinbox_begintime")
        self.gridLayout.addWidget(self.pinbox_begintime, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pinbox_choose = QtWidgets.QSpinBox(self.centralwidget)
        self.pinbox_choose.setMinimumSize(QtCore.QSize(0, 70))
        self.pinbox_choose.setSuffix("")
        self.pinbox_choose.setMinimum(1)
        self.pinbox_choose.setMaximum(20)
        self.pinbox_choose.setObjectName("pinbox_choose")
        self.gridLayout.addWidget(self.pinbox_choose, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.open_monitor = QtWidgets.QPushButton(self.centralwidget)
        self.open_monitor.setMinimumSize(QtCore.QSize(0, 70))
        self.open_monitor.setObjectName("open_monitor")
        self.gridLayout.addWidget(self.open_monitor, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_2.addWidget(self.pushButton_add, 0, 0, 1, 1)
        self.add_sel = QtWidgets.QPushButton(self.centralwidget)
        self.add_sel.setMinimumSize(QtCore.QSize(0, 70))
        self.add_sel.setObjectName("add_sel")
        self.gridLayout_2.addWidget(self.add_sel, 0, 1, 2, 1)
        self.add_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.add_posi.setMinimumSize(QtCore.QSize(0, 70))
        self.add_posi.setMaximum(100)
        self.add_posi.setObjectName("add_posi")
        self.gridLayout_2.addWidget(self.add_posi, 0, 2, 2, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout_2.addWidget(self.pushButton_delete, 1, 0, 2, 1)
        self.del_sel = QtWidgets.QPushButton(self.centralwidget)
        self.del_sel.setMinimumSize(QtCore.QSize(0, 70))
        self.del_sel.setObjectName("del_sel")
        self.gridLayout_2.addWidget(self.del_sel, 2, 1, 2, 1)
        self.dele_posi = QtWidgets.QSpinBox(self.centralwidget)
        self.dele_posi.setMinimumSize(QtCore.QSize(0, 70))
        self.dele_posi.setObjectName("dele_posi")
        self.gridLayout_2.addWidget(self.dele_posi, 2, 2, 2, 1)
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_show.setObjectName("pushButton_show")
        self.gridLayout_2.addWidget(self.pushButton_show, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_runtimeline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runtimeline.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton_runtimeline.setObjectName("pushButton_runtimeline")
        self.gridLayout_3.addWidget(self.pushButton_runtimeline, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setObjectName("textEdit_log")
        self.gridLayout_3.addWidget(self.textEdit_log, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setMinimumSize(QtCore.QSize(0, 100))
        self.load.setObjectName("load")
        self.verticalLayout.addWidget(self.load)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setMinimumSize(QtCore.QSize(0, 100))
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        self.load_modual = QtWidgets.QPushButton(self.centralwidget)
        self.load_modual.setMinimumSize(QtCore.QSize(0, 100))
        self.load_modual.setObjectName("load_modual")
        self.verticalLayout.addWidget(self.load_modual)
        self.pinbox_delaytime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pinbox_delaytime.setMinimumSize(QtCore.QSize(0, 100))
        self.pinbox_delaytime.setMaximum(1001.0)
        self.pinbox_delaytime.setObjectName("pinbox_delaytime")
        self.verticalLayout.addWidget(self.pinbox_delaytime)
        self.comboBox_delaytime_unit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_delaytime_unit.setMinimumSize(QtCore.QSize(0, 70))
        self.comboBox_delaytime_unit.setEditable(True)
        self.comboBox_delaytime_unit.setObjectName("comboBox_delaytime_unit")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.comboBox_delaytime_unit.addItem("")
        self.verticalLayout.addWidget(self.comboBox_delaytime_unit)
        self.ord_time = QtWidgets.QPushButton(self.centralwidget)
        self.ord_time.setMinimumSize(QtCore.QSize(0, 100))
        self.ord_time.setObjectName("ord_time")
        self.verticalLayout.addWidget(self.ord_time)
        self.mod_view = QtWidgets.QPushButton(self.centralwidget)
        self.mod_view.setMinimumSize(QtCore.QSize(0, 50))
        self.mod_view.setObjectName("mod_view")
        self.verticalLayout.addWidget(self.mod_view)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.textEdit_timeline = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_timeline.setObjectName("textEdit_timeline")
        self.verticalLayout_2.addWidget(self.textEdit_timeline)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setMinimumSize(QtCore.QSize(0, 100))
        self.update.setObjectName("update")
        self.horizontalLayout.addWidget(self.update)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_stoptime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_stoptime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_stoptime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_stoptime.setItemText(3, _translate("MainWindow", "ns"))
        self.comboBox_starttime.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_starttime.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_starttime.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_starttime.setItemText(3, _translate("MainWindow", "ns"))
        self.label_3.setText(_translate("MainWindow", "stoptime"))
        self.label_2.setText(_translate("MainWindow", "starttime"))
        self.pinbox_choose.setPrefix(_translate("MainWindow", "ttl"))
        self.label.setText(_translate("MainWindow", "timeline set"))
        self.open_monitor.setText(_translate("MainWindow", "open monitor"))
        self.pushButton_add.setText(_translate("MainWindow", "add"))
        self.add_sel.setText(_translate("MainWindow", "add at select position"))
        self.pushButton_delete.setText(_translate("MainWindow", "delete"))
        self.del_sel.setText(_translate("MainWindow", "delete after select position"))
        self.pushButton_show.setText(_translate("MainWindow", "show current timeline"))
        self.pushButton_runtimeline.setText(_translate("MainWindow", "add timeline to data_set"))
        self.label_5.setText(_translate("MainWindow", "log"))
        self.label_4.setText(_translate("MainWindow", "delete the initial set at the very first"))
        self.load.setText(_translate("MainWindow", "load"))
        self.save.setText(_translate("MainWindow", "save"))
        self.load_modual.setText(_translate("MainWindow", "add modual"))
        self.comboBox_delaytime_unit.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_delaytime_unit.setItemText(1, _translate("MainWindow", "ms"))
        self.comboBox_delaytime_unit.setItemText(2, _translate("MainWindow", "us"))
        self.comboBox_delaytime_unit.setItemText(3, _translate("MainWindow", "ns"))
        self.ord_time.setText(_translate("MainWindow", "ord_time"))
        self.mod_view.setText(_translate("MainWindow", "mod_view"))
        self.label_6.setText(_translate("MainWindow", "timeline"))
        self.update.setText(_translate("MainWindow", "update"))

